### ISSUE TITLE
Provide option to use external libraries rather that building duplicate copies

### ISSUE THREAD

**Issue by barracuda156** [polyfem/polysolve#37]
Could you please add options to use pre-installed Eigen3 and other libraries?

**Comment by jdumas** [comment]
Polysolve doesn't support this functionality when building it as a standalone project. But you can easily prevent Polysolve from fetching its own copy of Eigen by providing your own pre-built `Eigen3::Eigen` target before including Polysolve in your own project. E.g.:

```cmake
# Root CMakeLists.txt for MyProject
cmake_minimum_required(VERSION 3.24.0)
project(MyProject)

# Find pre-installed version of Eigen
find_package(Eigen3 REQUIRED)
if(NOT TARGET Eigen3::Eigen)
  message(FATAL_ERROR "find_package(Eigen3) failed to provide a Eigen3::Eigen CMake target")
endif()

# Include Polysolve library
include(FetchContent)
FetchContent_Declare(
    polysolve
    GIT_REPOSITORY https://github.com/polyfem/polysolve.git
    GIT_TAG 91f7e3a
)
FetchContent_MakeAvailable(polysolve)
```

Obviously you'll need to do the same for other dependencies required by Polysolve.

**Comment by barracuda156** [comment]
@jdumas

> Polysolve doesn't support this functionality when building it as a standalone project.

This is your project, of course, but for the record, it is pretty trivially fixable: https://github.com/macports/macports-ports/blob/master/math/polysolve/files/patch-CMakeLists.diff

**Comment by barracuda156** [comment]
> The problem is that "building everything from source" and "building against pre-installed system libs" are two different build philosophies

Macports allows to build everything from source (and that is what I do), and I think it is desirable – outside of Macports (or Freshports, etc.) – not to be forced to build numerous copies of the same libraries with every port (consider how many depend on `OpenBLAS` or `Eigen`). Otherwise it is a waste of compilation time, disk space, and turning system into a mess.
Essentially these are two unrelated questions: whether to build from source and whether to allow flexibility with dependencies.

> Your "patch", while well-intentioned, has two issues:

Well, I am did not make a PR with it (and neither intended to do so), it was just an illustration. (If I had a neat and universally applicable solution, I would have submitted it, but I don’t in this case.)

> not Cholmod, AMGCL, Spectra or MKL/Pardiso

Not all optional dependencies are in Macports at the moment. I may add more over time (or somebody else may as well).

**Comment by jdumas** [comment]
Yes I know the pros and cons of building from source vs building against pre-installed binaries. The current CMake is already flexible in the sense that you can easily override the dependencies by providing your own target before including polysolve. What is _not_ supported is building Polysolve as a top-level project against system libs, simply because there are too many dependencies that would need to be tested. If you want such a feature, it would need to be user-contributed. We can talk about how to implement it if you're interested, but we won't be implementing it ourselves.
